### ISSUE TITLE
Have the same session open in multiple windows/tabs/iframes simultaneously

### ISSUE THREAD

**Issue by psrpinto** [vector-im/hydrogen-web#1045]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have the same session open in multiple Hydrogen windows/tabs/iframes. Currently opening one tab with a session that is already open in another tab, results in the session being closed in the first tab. I would like for that not to happen, and to have Hydrogen fully functional with the same session in multiple simultaneous windows/tabs/iframes.

**Describe the solution you'd like**
I've written a proposal to address this issue in #1041. Please see proposal for details (in short, sync would run in a worker).

**Describe alternatives you've considered**
Please see #1041 for details on this.

## PRs

- [ ] https://github.com/vector-im/hydrogen-web/pull/1056

## TODO

- [ ] Merge https://github.com/vector-im/hydrogen-web/pull/1041
- [x] Make sure build system can handle [module workers](https://html.spec.whatwg.org/#module-worker-example)
- [x] `SyncProxy`
	- [x] Extract an `ISync` interface from `Sync` so there can be multiple implementations of `Sync`. This interface should define the public API of `Sync`.
	- [x] Add a `SyncProxy` which implements `ISync` (its methods won't be implemented yet)
	- [x] Create feature flag for _same session in multiple tabs_
	- [x] When the feature flag is enabled, instantiate `SyncProxy` instead of `Sync`
	- [x] Implement all methods of `ISync` in `SyncProxy`
- [x] Enable typescript checks on `sync-worker.ts`
- [x] Make it possible to set the `name` of the `SharedWorker`
- [ ] Iterate on `SyncWorker` + `SyncProxy`
	- [x] Implement `Worker` abstractions that would facilitate creating workers, communication between workers and main thread, etc.
	- [ ] ... WIP
- [ ] ... WIP

## Maybe later

- [ ] Rename `Olm` worker from `main.js` to `olm-worker.js`. Since we'll now have more than one worker in the codebase, having the `Olm` worker named `main.js` would be confusing. So we'll have an `olm-worker.js`, a `sync-worker.js`, etc.

**Comment by psrpinto** [comment]
Related to https://github.com/vector-im/hydrogen-web/issues/188
