### ISSUE TITLE
Support service worker in all environments (dev and sdk)

### ISSUE THREAD

**Issue by MidhunSureshR** [vector-im/hydrogen-web#1173]
For authenticated media, we need a service worker running in both dev and sdk builds.

```[tasklist]
### Tasks
- [x] `sw.js` in build should contain list of assets to cache but the list should be empty when building the sdk.
- [x] There should be no update dialog when code changes in development server or sdk build.
- [x] version returned by sw.js when used in sdk context should be correct (as per base-manifest.json)
- [x] `sw.js` is served during dev - done by custom rollup plugin
- [ ] ~~supply notification icon for sdk build~~ we can skip this until we want to support notifications in sdk
- [x] Unify defines in config and document why there's two sources of truth
- [x] Package sw.js in sdk build - preferably using the same plugin?
- [x] Document how to use the sdk with sw.js
- [x] During dev, version should be `develop` and global hash should be latest git commit.
```

**Comment by MidhunSureshR** [comment]
Done in https://github.com/element-hq/hydrogen-web/pull/1181, https://github.com/element-hq/hydrogen-web/pull/1179, https://github.com/element-hq/hydrogen-web/pull/1174
