### ISSUE TITLE
Document architecture concepts

### ISSUE THREAD

**Issue by bwindels** [vector-im/hydrogen-web#730]
Provide some documentation for the architecture around these topics:
 - [ ] Clean up current docs and docs/impl directory (move it somewhere else)
 - [ ] unit tests, runner and how to write and run them. how to run just one test.
 - [ ] MVVM and how we use it, tree of view models
 - [ ] observables (map, list & value)
   - how you should not iterate/call length before subscribing. how to chain. how to debug.
   - How updates can go over collection.
 - [ ] persistence layer, transaction usage
   - how timeline is stored
   - why we don't store reply preview events (fetched with /context, only if they haven't been fetched already)
 - [ ] timeline
   - how updates work
   - how to have custom tiles (with SDK)
   - spontanous updates (with setEmitUpdate)
   - changing the shape property will cause the view to be recreated
   - tile visibility, reacting to becoming in view
 - [ ] room list, 3 different tiles (joined, invite, created, ...)
 - [ ] room view model
   - grid view model & need for roomviewmodelobservable
 - [ ] Sync loop (with different stages, also called in Session)
 - [ ] E2EE
   - how olm receive to_device messages
   - how messages are decrypted when reading timeline
   - how new room keys are passed in sync loop
   - all steps in megolm decryption for batch decryption.
 - [x] Theming
   - base themes and derived themes.
   - Dark mode.
   - How to derive colors
   - How to color icons
   - How to add a theme to your config
 - [x] config file options 
 - [ ] logging & log viewer
 - [x] Generic UI utilities (TemplateView, ListView, ...)
 - [ ] SDK: what is considered the public API? Which files (e.g. not hashed files, those are only to be referenced by other files in the SDK), which methods are private (e.g. starting with _), what is supported by the sdk.
