### ISSUE TITLE
EPIC Color theming

### ISSUE THREAD

**Issue by fkwp** [vector-im/hydrogen-web#804]
Make it possible to define alternative color schemas for the existing Hydrogen theme, enabling things like a dark theme and branded colors for use cases like Chatterbox.

## Extra requirements
 - a way to derive colors from the base palette. The proposed syntax is to use css variables and find them with a postcss plugin in the format of `--base-variable--operation-argument`. We then create a <style> section that provides values for all these derived variables.
 - color svg icons with a named color variable

Proposed manifest format: https://gist.github.com/bwindels/16930ddb0bc0f0e14009f8880793f7bf

## Nomenclature
 - theme manifest: a json file describing all the css variables used (and derived in the css file it links to and also containing all themes (e.g. variants).
 - theme collection: a manifest and a css file representing one layout for Hydrogen. The manifest can define several themes by specifying values for css variables (e.g. colors, fonts, ...)
 - theme: a variant of a theme collection, see above

## Tasks
- [x] come up with manifest format
- [x] add postcss plugin to derive color variables
- [x] add postcss plugin to find and replace `url(icon.svg?primary=color-variable&secondary=other-color-variable)` to `var(--icon-url-1)` so we can insert colorized icons with css variables.
- [x] add postcss plugin to replace icon variables with alternative assets for svg icons with colors replaced for a given theme.
- [x] add rollup plugin to read theme manifest and output a css files for every theme.
- [x] Modify the existing element theme to work with new theme architecture, writing a manifest manifest and adding a light theme
- [x] Add a dark theme to the element theme
- [x] Detect whether user prefers dark or light theme when starting the app
- [x] Release MVP of theming with just light/dark support for a single theme, no settings UI
- [x] Read theme manifest locations to use in config file
- [x] Implement theme chooser in settings, enumerating different themes. Allow picking dark theme preference with system default | light | dark radio buttons per theme.
- [x] Release theme chooser
- [x] Add basic runtime theme support just for color variables
- [x] Add icon coloring support for runtime themes
