### ISSUE TITLE
Device verification

### ISSUE THREAD

**Issue by fkwp** [vector-im/hydrogen-web#828]
# High level description
Prevent man-in-the-middle attacks on e2ee by verification devices of other users. In the context of Hydrogen, this will also require a framework to establish trust of other devices, which is lacking currently.

# This is an EPIC issue. List of individual issues is below:

- [ ] list the devices of the user (e.g., in the member panel)
- [ ] be able to say for each device if it is trusted or not (red, green, black, shield)
- [ ] verify a device by comparing identity keys, store trust locally
- [ ] don't send to untrusted devices
