### ISSUE TITLE
Calls Support (MSC3401)

### ISSUE THREAD

**Issue by fkwp** [vector-im/hydrogen-web#946]
This is an epic issue. List of individual issues is below:

## Highlevel overview
Epic for getting [MSC3401](https://github.com/matrix-org/matrix-spec-proposals/pull/3401) (aka Element Call) support. This Epic covers mostly user facing "application" features.

```[tasklist]
### Linked Tickets
- [ ] https://github.com/vector-im/hydrogen-web/issues/967
- [ ] https://github.com/vector-im/hydrogen-web/issues/968
- [ ] https://github.com/vector-im/hydrogen-web/issues/969
- [ ] https://github.com/vector-im/hydrogen-web/issues/970
- [x] https://github.com/vector-im/hydrogen-web/issues/971
- [x] https://github.com/vector-im/hydrogen-web/issues/972
- [x] https://github.com/vector-im/hydrogen-web/issues/973
- [ ] https://github.com/vector-im/hydrogen-web/issues/894
- [ ] https://github.com/vector-im/hydrogen-web/issues/895
- [ ] https://github.com/vector-im/hydrogen-web/issues/896
- [ ] https://github.com/vector-im/hydrogen-web/issues/897
- [ ] https://github.com/vector-im/hydrogen-web/issues/898
- [ ] https://github.com/vector-im/hydrogen-web/issues/900
```

**Comment by Thatoo** [comment]
- [ ] Video Room (native call)

**Comment by toger5** [comment]
I think it makes sense to close this epic since it describes a path to full mesh calling and not the MatrixRTC approach.
It might make more sense to create a new epic adapted to the MatrixRTC msc's.

In its current state it might communicate that the plan for hydrogen is to add MSC3401 support to hydrogen which makes no sense to do before Livekit backed MatrixRTC.

@fkwp Feel free to open it again if you disagree or if there is a better approach.
